# Generated by Django 3.0.5 on 2020-05-01 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bg', '0003_notes_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='img',
            field=models.ImageField(upload_to='static/img'),
        ),
    ]
