# Generated by Django 3.0.5 on 2020-05-01 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bg', '0004_auto_20200501_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='img',
            field=models.ImageField(upload_to='bg/static/img'),
        ),
    ]
