# Generated by Django 3.0.5 on 2020-05-01 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bg', '0005_auto_20200501_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='img',
            field=models.ImageField(upload_to='blog_img'),
        ),
    ]
